name: CI

on: [ push, pull_request ]

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.6'
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-${{ env.pythonLocation }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.pythonLocation }}-pip-
      - uses: FedericoCarboni/setup-ffmpeg@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        id: setup-ffmpeg
      - name: Install dependencies
        run: |
          pip install wheel pytest pytest-xdist nbval
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -n 2 --junitxml=test_report.xml --nbval-lax . --dist loadscope
      - name: Upload test results
        if: always()
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: ./test_report.xml
          check_name: Test results
